### ISSUE TITLE
Statikus ellenőrzés

### ISSUE THREAD

**Issue by Kecsii** [BME-MIT-IET/Litteraux-iet-2019#3]
**Feladat:**
SonarQube futtatása a projekten, a jelzett hibák átnézése. A jelzett hibákkal kapcsolatban egyeztetés, majd a kiválasztott hibák javítása.

> **Kiadott feladat leírása:**
> Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarQube, FindBugs, VS Code Analyzer, Codacy, Coverity Scan...). Mivel az eszközök rengeteg hibát és figyelmeztetést találhatnak, ezért elég azok egy részét megvizsgálni és ha a csapat egyetért vele, akkor javítani. Törekedjetek arra, hogy különböző típusú, és lehetőleg nem triviális hibajelzéseket vizsgáljatok meg.

Wiki: 
https://github.com/BME-MIT-IET/Litteraux-iet-2019/wiki/%233---Statikus-ellen%C5%91rz%C3%A9s

**Comment by Pribzy** [comment]
Feladat befejezése
