### ISSUE TITLE
Tesztlefedettség mérése

### ISSUE THREAD

**Issue by Kecsii** [BME-MIT-IET/Litteraux-iet-2019#5]
**Feladat:**
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése.

> **Kiadott feladat leírása:**
> Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése (JaCoCo, OpenCover, Coveralls, Codecov.io...)

Wiki: 
https://github.com/BME-MIT-IET/Litteraux-iet-2019/wiki/%235-Tesztlefedetts%C3%A9g-m%C3%A9r%C3%A9se

**Comment by Pribzy** [comment]
Feladat befejezése
