### ISSUE TITLE
#6 Unit tesztek készítése

### ISSUE THREAD

**Issue by mecznerbalazs** [BME-MIT-IET/Litteraux-iet-2019#6]
A szoftver tesztkészletének bővítése

### Wiki:
[#6 - Unit tesztek készítése](https://github.com/BME-MIT-IET/Litteraux-iet-2019/wiki/%237-Unit-tesztek-k%C3%A9sz%C3%ADt%C3%A9se)

**Comment by Pribzy** [comment]
Feladat befejezve
